add_subdirectory(Actor)
add_subdirectory(AI)
add_subdirectory(Cooking)
add_subdirectory(Damage)
add_subdirectory(DLC)
add_subdirectory(UI)

target_sources(uking PRIVATE
  gameAmiiboMgr.cpp
  gameAmiiboMgr.h
  gameGearMgr.cpp
  gameGearMgr.h
  gameItemUtils.cpp
  gameItemUtils.h
  gameLastBossMgr.cpp
  gameLastBossMgr.h
  gameMaskController.cpp
  gameMaskController.h
  gameMotorcycleMgr.cpp
  gameMotorcycleMgr.h
  gameResetter.cpp
  gameRuneMgr.cpp
  gameRuneMgr.h
  gameResetter.h
  gameResidentActorMgr.cpp
  gameResidentActorMgr.h
  gameRumble.cpp
  gameRumble.h
  gameUnk_71024739d0.cpp
  gameUnk_71024739d0.h
  gameUnk_710090d904.cpp
  gameUnk_71008ba8d8.cpp
  gameUnk_71008ba8d8.h
  gameUnk_71008bbda4.cpp
  gameUnk_710246d058.cpp
  gameUnk_710246d058.h
  gamePlayReport.cpp
  gamePlayReport.h
  gameScene.cpp
  gameScene.h
  gameStageInfo.cpp
  gameStageInfo.h
  E3Mgr.cpp
  E3Mgr.h
)
