add_subdirectory(Action)
add_subdirectory(Behavior)
add_subdirectory(AI)
add_subdirectory(Query)

target_sources(uking PRIVATE
  aiActionFactories.cpp
  aiActionFactories.h
  aiActorLink.h
  aiAiFactories.cpp
  aiAiFactories.h
  aiBehaviorFactories.cpp
  aiBehaviorFactories.h
  aiAwarenessFilters.cpp
  aiAwarenessFilters.h
  aiGuardianAimBeamState.cpp
  aiGuardianAimBeamState.h
  aiMessage3DText.cpp
  aiMessage3DText.h
  aiQueryFactories.cpp
  aiQueryFactories.h
  aiUnk_71005D6D10.cpp
  aiUnk_71005D6D10.h
  aiUnk_71002C52DC.cpp
  aiUnk_71002C52DC.h
  aiUnk_71025ba778.cpp
  aiUnk_71025ba778.h
  aiUnk_71025be918.cpp
  aiUnk_71025be918.h
  aiUnk_7101e7c5d0.cpp
  aiUnk_7101e7c5d0.h
  aiUnk_71007024d4.cpp
  aiUnk_71023f18e8.cpp
  aiUnk_71023f18e8.h
  aiUnk_7100a921fc.cpp
  aiUnk_71007024d4.h
  aiUnk_7100710938.cpp
  aiUnk_7100711020.cpp
  aiUnk_7100711020.h
  aiUnk_71006F1DF0.cpp
  aiUnk_71007130BC.cpp
  aiUnk_71007130BC.h
  aiUnk_710087CE34.cpp
  aiUnk_710087CE34.h
  aiUnk_71006F1DF0.h
  aiUnk_710071edf8.cpp
  aiUnk_710071edf8.h
  aiUnk_7100724C64.cpp
  aiUnk_7100724C64.h
  aiUnk_710072BA90.cpp
  aiUnk_710072BA90.h
  aiUnk_7100736460.cpp
  aiUnk_7100736460.h
  aiUnk_710070284C.cpp
  aiUnk_710070284C.h
  aiUnk_710073033C.cpp
  aiUnk_710073033C.h
  aiUnk_71007368A4.cpp
  aiUnk_71007368A4.h
  aiUnk_71007377D4.cpp
  aiUnk_710071E0D8.cpp
  aiUnk_710071E0D8.h
  aiUnk_71006F55D8.cpp
  aiUnk_71005E0420.cpp
  aiUnk_71005E0420.h
  aiUnk_7100D3D3A8.cpp
  aiUnk_710073fa90.cpp
  aiUnk_710073CDFC.cpp
  aiUnk_710073CDFC.h
  aiUnk_7102384718.h
  aiUnk_71025b0578.cpp
  aiUnk_71025b2aa8.cpp
  aiUnk_71023da520.h
  aiUnk_7102357210.cpp
  aiUnk_7102357210.h
  aiUnk_7102357d20.cpp
  aiUnk_7102357d20.h
  aiUnk_7102450058.cpp
  aiUnk_7102450058.h
  aiUnk_7102450298.cpp
  aiUnk_710244ed58.cpp
  aiUnk_7102431fa8.h
  aiUnk_7102451120.cpp
  aiUnk_7102451120.h
  aiUnk_7102450d10.cpp
  aiUnk_7102450d10.h
  aiUnk_7102450fa8.cpp
  aiUnk_7102450fa8.h
  aiUnk_71024f15c0.cpp
  aiUnk_71024f15c0.h
  aiUnk_71024f15f8.cpp
  aiUnk_71024f15f8.h
  aiUnk_71025afb58.h
  aiUnk_71025b1808.cpp
  aiUnk_71025b1808.h
  aiUnk_7102450648.cpp
  aiUnk_71024507c8.cpp
  aiUnk_7102450828.cpp
  aiUnkDamageCallbacks.cpp
  aiUnkDamageCallbacks.h
  aiUnkMessagePayloads.h
  aiUnk_7102450af8.cpp
  aiUnk_7102450bb8.cpp
)
