add_subdirectory(Action)
add_subdirectory(Behavior)
add_subdirectory(AI)
add_subdirectory(Query)

target_sources(uking PRIVATE
  aiActionFactories.cpp
  aiActionFactories.h
  aiActorLink.h
  aiAiFactories.cpp
  aiAiFactories.h
  aiAwarenessFilters.cpp
  aiAwarenessFilters.h
  aiGuardianAimBeamState.cpp
  aiGuardianAimBeamState.h
  aiMessage3DText.cpp
  aiMessage3DText.h
  aiQueryFactories.cpp
  aiQueryFactories.h
  aiUnk_71005D6D10.cpp
  aiUnk_71005D6D10.h
  aiUnk_710071edf8.cpp
  aiUnk_710071edf8.h
  aiUnk_7100724C64.cpp
  aiUnk_7100724C64.h
  aiUnk_710072BA90.cpp
  aiUnk_710072BA90.h
  aiUnk_71007368A4.cpp
  aiUnk_71007368A4.h
  aiUnk_71007377D4.cpp
  aiUnk_7102357210.cpp
  aiUnk_7102357210.h
  aiUnk_7102357d20.cpp
  aiUnk_7102357d20.h
  aiUnk_7102431fa8.h
  aiUnk_7102451120.cpp
  aiUnk_7102451120.h
  aiUnk_7102450d10.cpp
  aiUnk_7102450d10.h
  aiUnk_7102450fa8.cpp
  aiUnk_7102450fa8.h
  aiUnk_71024f15c0.cpp
  aiUnk_71024f15c0.h
  aiUnk_71025afb58.h
  aiUnk_7102450648.cpp
  aiUnk_71024507c8.cpp
  aiUnk_7102450828.cpp
  aiUnkDamageCallbacks.cpp
  aiUnkDamageCallbacks.h
  aiUnkMessagePayloads.h
  aiUnk_7102450af8.cpp
  aiUnk_7102450bb8.cpp
)
