project(aal CXX ASM)

add_library(aal OBJECT
  include/aal/aalActiveSoundLimiter.h
  include/aal/aalArbiter.h
  include/aal/aalAssetInfo.h
  include/aal/aalAuxBusMgr.h
  include/aal/aalAudioMetaReader.h
  include/aal/aalAttenuationComponentListReflexer.h
  include/aal/aalAttenuationReader.h
  include/aal/aalCone.h
  include/aal/aalCurveReader.h
  include/aal/aalResourceHeader.h
  include/aal/aalDeviceType.h
  include/aal/aalEmitter.h
  include/aal/aalFadeCurveType.h
  include/aal/aalFinalFxMgr.h
  include/aal/aalFxDelayParamSetter.h
  include/aal/aalFxParamSetter.h
  include/aal/aalGroup.h
  include/aal/aalGroupLimiter.h
  include/aal/aalGroupReader.h
  include/aal/aalGroupMgr.h
  include/aal/aalHandle.h
  include/aal/aalFinalFxCtrl.h
  include/aal/aalFinalOutputMeasure.h
  include/aal/aalInterior.h
  include/aal/aalInteriorSet.h
  include/aal/aalOutputDevice.h
  include/aal/aalOutputMode.h
  include/aal/aalISpeakerBalanceSupplier.h
  include/aal/aalListenerDirectivity.h
  include/aal/aalListenerMgr.h
  include/aal/aalIUnifiable.h
  include/aal/aalMarkerController.h
  include/aal/aalMeter.h
  include/aal/aalNamedObj.h
  include/aal/aalRequestIntervalLimiter.h
  include/aal/aalRequestSoundLimiter.h
  include/aal/aalRollOffCurve.h
  include/aal/aalSettings.h
  include/aal/aalShape.h
  include/aal/aalShapeMgr.h
  include/aal/aalSoundController.h
  include/aal/aalSoundParam.h
  include/aal/aalSoundSource.h
  include/aal/aalSoundSourceUnifier.h
  include/aal/aalSpatialCalculator.h
  include/aal/aalSpeakerBalanceUnifierArea.h
  include/aal/aalSpeakerBalanceUnifierMgr.h
  include/aal/aalSpatialPlayingParamPool.h
  include/aal/aalSpatialSetting.h
  include/aal/aalStopWatch.h
  include/aal/aalSystem.h
  include/aal/aalSystemAccessor.h
  include/aal/aalTimedFader.h
  src/aalActiveSoundLimiter.cpp
  src/aalAttenuationComponentListReflexer.cpp
  src/aalAttenuationReader.cpp
  src/aalAudioMetaReader.cpp
  src/aalCone.cpp
  src/aalConeFactory.cpp
  src/aalCurveReader.cpp
  src/aalArbiter.cpp
  src/aalAuxBusMgr.cpp
  src/aalEmitter.cpp
  src/aalFinalFxMgr.cpp
  src/aalFxDelayParamSetter.cpp
  src/aalFxParamSetter.cpp
  src/aalGroup.cpp
  src/aalGroupFolder.cpp
  src/aalGroupLimiter.cpp
  src/aalGroupReader.cpp
  src/aalGroupMgr.cpp
  src/aalSpatialCalculator.cpp
  src/aalHandle.cpp
  src/aalInterior.cpp
  src/aalListenerDirectivity.cpp
  src/aalInteriorSet.cpp
  src/aalOutputDevice.cpp
  src/aalISpeakerBalanceSupplier.cpp
  src/aalMarkerController.cpp
  src/aalMeter.cpp
  src/aalNamedObj.cpp
  src/aalRequestIntervalLimiter.cpp
  src/aalRequestSoundLimiter.cpp
  src/aalRollOffCurve.cpp
  src/aalShape.cpp
  src/aalShapeCapsule.cpp
  src/aalShapeCube.cpp
  src/aalShapeSegment.cpp
  src/aalShapeSphere.cpp
  src/aalSoundGroup.cpp
  src/aalSettings.cpp
  src/aalSimpleTimedFader.cpp
  src/aalStopWatch.cpp
  src/aalPlayingStateController.cpp
  src/aalSoundController.cpp
  src/aalSoundParam.cpp
  src/aalSystem.cpp
  src/aalTimedFader.cpp
  src/aalSoundSource.cpp
  src/aalSpatialPlayingParam.cpp
  src/aalSpatialPlayingParamPool.cpp
  src/aalSpatialSetting.cpp
  src/aalSpeakerBalanceUnifierArea.cpp
  src/aalSpeakerBalanceUnifierAreaSegment.cpp
  src/dummy.cpp
)

target_compile_options(aal PRIVATE -fno-exceptions)
target_compile_options(aal PRIVATE -fno-strict-aliasing)
target_compile_options(aal PRIVATE -Wno-invalid-offsetof)
target_include_directories(aal PUBLIC include/)

if(NOT TARGET sead)
  add_subdirectory(../sead)
endif()
target_link_libraries(aal PUBLIC sead)
